### ISSUE TITLE
[PE-D][Tester C] Small issue when entering empty task name and tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-1/tp#164]
After selecting a patient and entering the task state, if the user try to add an empty todo task and an empty tag, the program will regard "/tag" as the name of the todo task. This is not a big deal but perhaps the feature can be done in a more proper way?

Here are the commands that cause the issue:
![image.png](https://raw.githubusercontent.com/MatchaRRR/ped/main/files/f994b471-b457-4e3c-8e4e-1ced649289be.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: MatchaRRR/ped#4

**Comment by lowjunchen** [comment]
this issue has been addressed in the latest pull request
