### ISSUE TITLE
[PE-D][Tester D] Input not restricted to be of type time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-1/tp#170]
![Screenshot 2024-11-08 at 4.48.51 PM.png](https://raw.githubusercontent.com/Oshen27/ped/main/files/b921cbbb-f4ae-42be-8bd7-5b87099bcc43.png)

The input after the /every clause can be anything, where it should be of a quantity of time instead

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Oshen27/ped#6

**Comment by Metanyu** [comment]
Thank you for your input. The `repeat` command is designed to be like that, because we figured in real life context, a lot of cases would be similar to the example you provided - which is not set to be a particular time during the day. Thus, we won't be making changes to the designed feature.
