### ISSUE TITLE
[PE-D][Tester B] Help function has printing issues in select mode.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T11-1/tp#171]
The help function in the select mode prints the following. but when i used the add command in the select mode, it didn't do anything. I think you meant todo?

![image.png](https://raw.githubusercontent.com/C2linaung/ped/main/files/cffe43cb-31ff-4e0d-aaff-c370b51d5401.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: C2linaung/ped#8

**Comment by Metanyu** [comment]
Closing this as fixed in #212
