### ISSUE TITLE
[PE-D][Tester B] second diagram for add task command issue.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-1/tp#199]
Returns are not dotted. Additionally, by convention, your returns/ whatever words you write to that line should be situated closer to the arrow of that line. this is so that we know which line the words are for.

![image.png](https://raw.githubusercontent.com/C2linaung/ped/main/files/eee33036-97d4-440c-a2e4-d350b42e2f13.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: C2linaung/ped#15

**Comment by Metanyu** [comment]
Hi @C2linaung, thank you for finding a bug in my diagram! However I couldn't find the return line which you mentioned is not dotted. I would appreciate it if you could point that one out.
