### ISSUE TITLE
[PE-D][Tester B] class diagram error for tag patient feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-1/tp#202]
The circled items should be closer to the arrow. especially "manages" 
![image.png](https://raw.githubusercontent.com/C2linaung/ped/main/files/e50da3bf-8222-41ef-bc7d-d77bb4d13337.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: C2linaung/ped#17

**Comment by NCF3535** [comment]
Hi @C2linaung can I clarify on the need to be near the arrow for class diagrams? in the lecture notes, associations are at the centre with the arrow head at the text. Understand that should be our mistake and not that it needs to be close to the arrowhead. Do clarify and let us know.
![image](https://github.com/user-attachments/assets/9a661bba-a849-4775-ada9-1ea38db570d0)
![image](https://github.com/user-attachments/assets/ef44da1b-8435-4b92-a6f9-d081c2ebfb2c)
