### ISSUE TITLE
Bug fix impact on jun chens test cases.

### ISSUE THREAD

**Issue by kennethszj** [AY2425S1-CS2113-T11-1/tp#96]
### 1. Problem Overview  
- **Issue with the Back Command**: Previously, when executing the BackCommand, the UI didn’t reflect the expected state changes. Specifically, if a patient was selected and the user issued a "back" command, the UI didn’t properly reset.  
- **Cause**: This is because the BackCommand wasn’t clearing the selected patient, meaning the app will hold onto data for a specific patient even though the state had changed. The UI would continue to display the specific patient information despite the user being in main state.

### 2. Solution and Refactoring  
- **Clearing the Selected Patient**: to address this, BackCommand now clears the selected patient when switching to the main state.  
- **Refactoring**: **To enable this functionality, I refactored the code to pass the Hospital instance through the Parser and into the BackCommand.**

### 3. Impact on Jun Chen's Test Cases  **(IMPORTANT)**
- Since the Parser and BackCommand now require a Hospital instance to function correctly, existing test cases that create instances of these classes without Hospital will no longer work.  
- **Resolution**: To resolve this, we’ll need to update the test cases to include a Hospital instance. I wanted help to do it but i would have overridden your code which may affect your marks. however, all you need to do is the following:
- previously you did: Command returnedCommand7 = new Parser().parseCommand("mark 1",taskState);
- now you need to change to:
Hospital hospital = new Hospital();
Parser parser = new Parser(hospital);
Command returnedCommand7 = parser.parseCommand("mark 1", taskState);

**Comment by lowjunchen** [comment]
can i check if you pushed the code containing this change yet?

**Comment by lowjunchen** [comment]
This issue is no longer relevant as the code causing all these problems have been removed.
